# Generated by Django 4.0.6 on 2022-10-14 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforum',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7caed1ac-5cbf-4e41-8dbf-32047ed0d253'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0fd80d6d-2df0-44ae-8632-20f754c5f183'), primary_key=True, serialize=False),
        ),
    ]
