# Generated by Django 4.0.6 on 2022-10-14 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2297b782-0e07-44ca-89dc-9b2e529e0b6a'), primary_key=True, serialize=False),
        ),
    ]
