# Generated by Django 4.0.6 on 2022-10-14 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_guestforumcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54bde11a-c4d5-40aa-802a-4191d2142078'), primary_key=True, serialize=False),
        ),
    ]
