# Generated by Django 4.0.6 on 2022-09-29 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_id_alter_forum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
