# Generated by Django 4.0.6 on 2022-10-14 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_guestforum_id_alter_guestforumcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforum',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db1a56dd-542a-4694-9a2e-43e56ee20866'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('934ae247-9fdb-42e9-9861-153f0c529b4d'), primary_key=True, serialize=False),
        ),
    ]
