# Generated by Django 4.0.6 on 2022-10-01 15:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_forum_id_alter_forum_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestForum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('title', models.CharField(max_length=400)),
                ('body', ckeditor.fields.RichTextField()),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='guest_forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
