# Generated by Django 4.0.6 on 2022-10-14 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_guestforumcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61bc4835-2f99-46ff-84e5-1b966dcbf9f2'), primary_key=True, serialize=False),
        ),
    ]
