# Generated by Django 4.0.6 on 2022-10-03 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_guestforumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestforumcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
