# Generated by Django 4.0.6 on 2022-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
